package astgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"sort"
)

// declEntry is either an ast.Decl or a raw source string.
type declEntry struct {
	decl ast.Decl // AST declaration (nil if raw)
	raw  string   // raw Go source text (empty if AST)
}

// FileBuilder constructs a complete Go source file using go/ast.
type FileBuilder struct {
	fset        *token.FileSet
	pkg         string
	imports     map[string]string // path → alias (empty string for default)
	decls       []declEntry
	generatedBy string // tool name for "Code generated by" header
}

// SetGeneratedBy sets the tool name for the generated file header comment.
func (fb *FileBuilder) SetGeneratedBy(tool string) {
	fb.generatedBy = tool
}

// NewFileBuilder creates a new file builder for the given package name.
func NewFileBuilder(packageName string) *FileBuilder {
	return &FileBuilder{
		fset:    token.NewFileSet(),
		pkg:     packageName,
		imports: make(map[string]string),
	}
}

// AddImport adds an import path to the file.
func (fb *FileBuilder) AddImport(path string) {
	if _, exists := fb.imports[path]; !exists {
		fb.imports[path] = ""
	}
}

// AddNamedImport adds a named import to the file.
func (fb *FileBuilder) AddNamedImport(alias, path string) {
	fb.imports[path] = alias
}

// AddDecl adds an AST declaration to the file.
func (fb *FileBuilder) AddDecl(decl ast.Decl) {
	fb.decls = append(fb.decls, declEntry{decl: decl})
}

// AddRawDecl adds a raw Go source declaration to the file.
// The source should be a complete declaration (type, const, var, func).
func (fb *FileBuilder) AddRawDecl(source string) {
	fb.decls = append(fb.decls, declEntry{raw: source})
}

// Build generates the formatted Go source code.
// Each declaration is rendered individually to avoid cross-decl position conflicts.
func (fb *FileBuilder) Build() ([]byte, error) {
	var buf bytes.Buffer
	cfg := &printer.Config{
		Mode:     printer.UseSpaces | printer.TabIndent,
		Tabwidth: 8,
	}

	// Generated file header
	if fb.generatedBy != "" {
		buf.WriteString(fmt.Sprintf("// Code generated by %s; DO NOT EDIT.\n\n", fb.generatedBy))
	}

	// Package declaration
	buf.WriteString(fmt.Sprintf("package %s\n\n", fb.pkg))

	// Imports
	if len(fb.imports) > 0 {
		importDecl := fb.buildImportDecl()
		if err := cfg.Fprint(&buf, fb.fset, importDecl); err != nil {
			return nil, err
		}
		buf.WriteString("\n\n")
	}

	// Render each declaration individually
	for _, entry := range fb.decls {
		if entry.raw != "" {
			buf.WriteString(entry.raw)
		} else if entry.decl != nil {
			// Extract and print doc comments manually to avoid position issues
			// when rendering individual decls outside of a File context.
			switch d := entry.decl.(type) {
			case *ast.GenDecl:
				if d.Doc != nil {
					for _, c := range d.Doc.List {
						buf.WriteString(c.Text + "\n")
					}
					d.Doc = nil
				}
			case *ast.FuncDecl:
				if d.Doc != nil {
					for _, c := range d.Doc.List {
						buf.WriteString(c.Text + "\n")
					}
					d.Doc = nil
				}
			}
			if err := cfg.Fprint(&buf, fb.fset, entry.decl); err != nil {
				return nil, err
			}
		}
		buf.WriteString("\n")
	}

	// Format the output
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("failed to format generated code: %w", err)
	}

	return formatted, nil
}

func (fb *FileBuilder) buildImportDecl() *ast.GenDecl {
	// Sort import paths for deterministic output
	paths := make([]string, 0, len(fb.imports))
	for path := range fb.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	specs := make([]ast.Spec, 0, len(paths))
	for _, path := range paths {
		alias := fb.imports[path]
		spec := &ast.ImportSpec{
			Path: StringLit(path),
		}
		if alias != "" {
			spec.Name = Ident(alias)
		}
		specs = append(specs, spec)
	}

	return &ast.GenDecl{
		Tok:    token.IMPORT,
		Lparen: 1, // Force parenthesized import
		Specs:  specs,
	}
}
