// Code generated by schema-gen; DO NOT EDIT.

package acp

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Describes a single environment variable for an [`AuthMethodEnvVar`] authentication method.
type AuthEnvVar struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	Label    string         `json:"label,omitempty"`
	Name     string         `json:"name"`
	Optional bool           `json:"optional,omitempty"`
	Secret   bool           `json:"secret,omitempty"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Environment variable authentication method.
//
// The user provides credentials that the client passes to the agent as environment variables.
type AuthMethodEnvVar struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description string         `json:"description,omitempty"`
	ID          string         `json:"id"`
	Link        string         `json:"link,omitempty"`
	Name        string         `json:"name"`
	Vars        []AuthEnvVar   `json:"vars"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Terminal-based authentication method.
//
// The client runs an interactive terminal for the user to authenticate via a TUI.
type AuthMethodTerminal struct {
	Meta        map[string]any    `json:"_meta,omitempty"`
	Args        []string          `json:"args,omitempty"`
	Description string            `json:"description,omitempty"`
	Env         map[string]string `json:"env,omitempty"`
	ID          string            `json:"id"`
	Name        string            `json:"name"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Notification to cancel an ongoing request.
//
// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/cancellation)
type CancelRequestNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	RequestID RequestID      `json:"requestId"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Cost information for a session.
type Cost struct {
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// A boolean on/off toggle session configuration option payload.
type SessionConfigBoolean struct {
	CurrentValue bool `json:"currentValue"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Token usage information for a prompt turn.
type Usage struct {
	CachedReadTokens  *int64 `json:"cachedReadTokens,omitempty"`
	CachedWriteTokens *int64 `json:"cachedWriteTokens,omitempty"`
	InputTokens       int64  `json:"inputTokens"`
	OutputTokens      int64  `json:"outputTokens"`
	ThoughtTokens     *int64 `json:"thoughtTokens,omitempty"`
	TotalTokens       int64  `json:"totalTokens"`
}

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Context window and cost update for a session.
type UsageUpdate struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Cost *Cost          `json:"cost,omitempty"`
	Size int64          `json:"size"`
	Used int64          `json:"used"`
}
